### ISSUE TITLE
Setup checklist

### ISSUE THREAD

**Issue by robbywashere-zz** [robbywashere/node-js-sample#2]
- [x] Prompt Existing Repo Name

## Heroku

- [x] Prompt New Heroku App Name
- [x] Login to Heroku using the 'lucid-int' integration account.
    Create an application for the staging environment and name it (following the convention) for the intended usage of this request, adding the suffix '-stg'. AND
    Create an application for the production environment and name it (following the convention) for the intended usage of this request, adding the suffix '-prod'.
- [ ] If custom domain is requested, navigate to lusa-services-app in Heroku to add the custom domain to the list of Auth0 Allowed Callback Urls. Follow the Lucid_Auth0_Configuration job aide for more details
- [x] Prompt New Pipeline Name
- [x] Go into the production application's deploy tab and choose "New Pipeline". Create a new Heroku pipeline following the Heroku Pipeline naming convention.
- [x] Add an application to the pipeline 'staging' state. Choose the staging application previously created.
- [x] Connect the Heroku pipeline to the associated GitHub repository.
- [ ] Enable 'Review Apps' in the pipeline, automatically provisioning applications off the 'staging' application. 
    Select the option to automatically create apps off of pull requests.
    Choose the context menu for the staging application and select 'Configure Automatic Deployments' - select the 'master' branch.
- [ ] Lock the staging application.
- [x] Add 'Papertrail' Add-on at the 'Fixa' tier level to the staging application.
    Add 'Redis' Add-on at the 'Premium 0' tier level to the staging application.
- [x] Add 'AUTH0_CLIENT_ID', 'AUTH0_CLIENT_SECRET','AUTH_ENABLED=true', 'SESSION_SECRET', 'NODE_MODULES_CACHE=false' as configuration variables on the staging application.
- [ ] Execute the job aid for 'sync' on the staging application.
- [x] Deploy the staging application from the master branch.
- [x] “Open App” to verify the staging application is available.
- [ ] Lock the production application.
- [x] Add 'Papertrail' Add-on at the 'Fixa' tier level to the production application.
    Add 'Redis' Add-on at the 'Premium 0' tier level to the production application.
- [x] Add 'SSL' Add-on to the production application.
- [x] Add 'AUTH0_CLIENT_ID', 'AUTH0_CLIENT_SECRET', 'AUTH_ENABLED=true', 'NEW_RELIC_LICENSE_KEY', 'ENABLE_NEW_RELIC', 'NEW_RELIC_APP_NAME', 'MAINTENANCE_PAGE_URL' as configuration variables on the production application.
- [ ] Add the custom domain to the production application.
- [x] Promote the staging slug into production.
- [ ] Add SSL certificate to the production application.
- [ ] Verify the SSL certificate is trusted by running 'heroku certs:info –a {app-name}'
- [ ] Verify the DNS binding request for custom domain previously submitted is correct.
- [ ] Execute the job aid for 'sync' on the production application.
- [x] “Open App” to verify the production application is available.
- [ ] Configure Dynatrace for availability monitoring. Refer to the Dynatrace/Gomez configuration job aid. 
- [x] Set the configuration variable 'ENABLE_NEW_RELIC' to 'false' on the production application.
- [x] Enable maintenance mode for the production application.
- [x] Set the configuration variable 'AUTH_ENABLED' to 'false' on the production application.
